# Ayna Docker Standard - Development Compose
# Version: 1.0.0
#
# Hot reload, mounted source code, debug tools

services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
      target: development
    container_name: ${PROJECT_NAME}-api
    volumes:
      - ../src:/app  # Mount source for hot reload
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - DEBUG=true
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./dev.db}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME}-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Optional: PostgreSQL for local development
  # Uncomment if needed
  # db:
  #   image: postgres:16-alpine
  #   container_name: ${PROJECT_NAME:-myproject}-db-dev
  #   environment:
  #     - POSTGRES_USER=${DB_USER:-postgres}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
  #     - POSTGRES_DB=${DB_NAME:-app}
  #   ports:
  #     - "${DB_PORT:-5432}:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - app-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  # postgres-data:
