# Ayna Docker Standard - Production Compose
# Version: 1.0.0
#
# Built images, health checks, no volume mounts

services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
      target: production
    image: ${PROJECT_NAME}-api:latest
    container_name: ${PROJECT_NAME}-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - DEBUG=false
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME}-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M

  # Caddy reverse proxy (optional - use external Caddy if preferred)
  # caddy:
  #   image: caddy:2-alpine
  #   container_name: ${PROJECT_NAME:-myproject}-caddy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ../caddy/Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddy-data:/data
  #     - caddy-config:/config
  #   networks:
  #     - app-network
  #   depends_on:
  #     - api

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  # caddy-data:
  # caddy-config:
